// ─────────────────────────────────────────────────────────────────────────────
// Default config — generated profiles override these browser-safe fallbacks.
// ─────────────────────────────────────────────────────────────────────────────
const FALLBACK_DEFAULT = {
  person1Name: 'Person 1',
  person2Name: '',
  hasSpouse: false,
  nathanAge: 35,
  tanyaAge: 35,
  retireNathanAge: 55,
  retireTanyaAge: 55,
  portfolioTotal: 500000,
  nathanSalaryBase: 120000,
  tanyaSalaryBase: 0,
  nathanRsuAnnual: 0,
  tanyaRsuAnnual: 0,
  rsuVestingYears: 4,
  incomeGrowthReal: 0.02,
  effectiveIncomeTax: 0.28,
  baseSpending: 80000,
  spendingGrowthReal: 0.005,
  retirementSpendingFraction: 0.85,
  healthcareAnnual: 15000,
  medicareAge: 65,
  numKids: 0,
  firstKidYear: 0,
  childcareAnnual: 25000,
  k12Annual: 5000,
  collegeContribution: 50000,
  upgradeHouse: false,
  upgradeYear: 5,
  upgradeAdditionalCost: 0,
  ssNathanAnnual: 20000,
  ssTanyaAnnual: 0,
  ssClaimAge: 67,
  ssReductionFactor: 1.0,
  equityReturnNominal: 0.09,
  equityStd: 0.17,
  bondReturnNominal: 0.04,
  inflation: 0.03,
  equityFractionWorking: 0.85,
  equityFractionRetired: 0.60,
  simulationMethod: 'monte_carlo',
  withdrawalStrategy: 'constant_dollar',
  withdrawalRate: 0.04,
  swr: 0.04,
  years: 70,
  mcRuns: 300,
  upperGuardrail: 0.05,
  lowerGuardrail: 0.03,
  guardrailCut: 0.10,
  dynamicSpendingFloor: -0.025,
  dynamicSpendingCeiling: 0.05,
  gkCapitalPreservation: 1.20,
  gkProsperity: 0.80,
  gkAdjustment: 0.10,
  gkSunsetYears: 15,
  spendingFloor: 0.75,
  spendingCeiling: 1.20,
};
const DEFAULT = { ...FALLBACK_DEFAULT };
const MONARCH_META = {};

let cfg = { ...DEFAULT };

export { FALLBACK_DEFAULT, DEFAULT, MONARCH_META, cfg };
